services:
  timeline-generator:
    build: .
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:3000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3