services:
  timeline-generator:
    build: .
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0/docs"]
      interval: 30s
      timeout: 10s
      retries: 3